stages:
  - build
  - test
  
cache:
  paths:
     - ./src/.gradle/wrapper
     - ./src/.gradle/caches

buildjob:
  stage: build
  script:
    - cd ./src/
    - chmod +x gradlew
    - ./gradlew ':Lightx00.Server:assemble'
    - ./gradlew ':Lightx00.Client:assemble'


testjob:
  stage: test
  script:
    - cd ./src/
    - chmod +x gradlew
    - ./gradlew ':Lightx00.Server:check'
  only:
    - develop
    - master