stages:
  - build
  - test
  
cache:
  paths:
     - ./src/Lightx00.Client/.gradle/wrapper
     - ./src/Lightx00.Client/.gradle/caches
     - ./src/Lightx00.Server/.gradle/wrapper
     - ./src/Lightx00.Server/.gradle/caches

buildjob:
  stage: build
  script:
    - cd ./src/Lightx00.Client
    - chmod +x gradlew
    - ./gradlew assemble
    - cd ../../src/Lightx00.Server
    - chmod +x gradlew
    - ./gradlew assemble

testjob:
  stage: test
  script:
    - cd ./src/Lightx00.Client
    - chmod +x gradlew
    - ./gradlew check
    - cd ../../src/Lightx00.Server
    - chmod +x gradlew
    - ./gradlew check
  only:
    - develop
    - master